version: '3.8'

services:
  mcp-clickhouse:
    container_name: mcp-clickhouse
    image: mcp-clickhouse:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command:
      ["--transport", "${TRANSPORT}", "--port", "${PORT}"]